#!/bin/bash
# input from fb.pl
# output augments fb.pl
temp=_temp_${RANDOM}
temp2=_temp_${RANDOM}

### move result into fb.pl (without overwrite problems)
temp=temp_${RANDOM}

#$1/layerallcontains_query.bash >${temp}

####### 
temp=temp${RANDOM}
# layer 3


cat >${temp}.pl <<'~~~'
:- use_module(library(http/json)).
?- consult(fb).
?- consult("shapes").
?- consult("onSameDiagram").
?- consult("inside").
?- consult("names").
?- consult("ports").
?- consult("contains").
query_helper(Parent,Child):-
contains(Parent,Child),
true.
query:-
bagof([Parent,Child],query_helper(Parent,Child),Bag),
json_write(user_output,Bag,[width(128)]).
~~~
cat >${temp}.js <<'~~~'
const fs = require ('fs');
var rawText = fs.readFileSync ('/dev/fd/0');
var parameters = JSON.parse(rawText);
parameters.forEach (p => {
  var Parent = p [0];
var Child = p [1];
  
if (true) { console.log (`das_fact(contains,${Parent},${Child}).`);};
});
  
~~~
swipl -g "consult(${temp})." -g 'query.' -g 'halt.' | node ${temp}.js
rm -f ${temp}.pl
rm -f ${temp}.js
####### 



$1/appendToFb ${temp}
# cat $temp
# cat fb.pl $temp >$temp2
# mv $temp2 fb.pl

rm -f ${temp}
